---
- name: launch an instance
  hosts: all
  gather_facts: false
  serial: "{{ serial_batch_size | default(3) }}"
  vars_files:
    - clouds.yaml
    - vm_settings.yaml
  vars_prompt:
      - name: openstack_password
        prompt: "Password for Openstack"
  tasks:
    - name: "Creates {{ ansible_nodename }} VMs on Openstack."
      ansible.builtin.include_tasks: manage_vm.yml
